name: Deploy uat

on:
  push:
    branches: [uat]

jobs:
  deploy:
    uses: Sud-Austral/infra-docker-base/.github/workflows/deploy-uat.yml@main
    with:
      app_name: ${{ github.event.repository.name }}

